@host = https://pokeapi.co/api/v2
@name = {{pokemons.response.body.results[0].name}}
@spriteUrl = {{pokemon.response.body.sprites.other.dream_world.front_default}}


## All APIs
GET {{host}} HTTP/1.1
Accept: application/json


###


## All Pokemons
# @name pokemons
GET {{host}}/pokemon HTTP/1.1
Accept: application/json

###


## Pokemon by ID
# @name pokemon
GET {{host}}/pokemon/1 HTTP/1.1
Accept: application/json


###


## Pokémon Ability
# @name ability
GET {{host}}/ability/61 HTTP/1.1
Accept: application/json

###

## Characteristic
# @name characteristic
GET {{host}}/characteristic/2 HTTP/1.1
Accept: application/json


###

## Item
# @name item
GET {{host}}/item/222/ HTTP/1.1
Accept: application/json


###


## Language
GET {{host}}/language/9 HTTP/1.1
Accept: application/json